<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>
    </AssemblyVersion>
    <FileVersion>
    </FileVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

	<PropertyGroup>
		<Version>8.26.1802</Version>
		<Copyright>2026, Energienetze Steiermark</Copyright>
		<PackageProjectUrl>https://github.com/e-netze/datalinq</PackageProjectUrl>
		<RepositoryUrl>https://github.com/e-netze/datalinq</RepositoryUrl>
		<Authors>Jürgen Gstaltmaier</Authors>
		<Company />
		<Product />
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="E.Standard.Vault" Version="1.25.1102" />
    <PackageReference Include="Neo4j.Driver" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>