services:
  datalinq-code:
    image: datalinqcode:latest
    container_name: datalinq-code
    ports:
      - "5678:8080"
    environment:
      DataLinq.Code__Instances__0__Name: "DataLinq Dev"
      DataLinq.Code__Instances__0__Description: "DataLinq Dev Instanz für Dashboards & Reports"
      DataLinq.Code__Instances__0__LoginUrl: "http://localhost:6789"
      DataLinq.Code__Instances__0__LogoutUrl: "http://localhost:6789"
      DataLinq.Code__Instances__0__CodeApiClientUrl: "http://datalinq-api:8080"

  datalinq-api:
    image: datalinqapi:latest
    container_name: datalinq-api
    ports:
      - "6789:8080"
    environment:
      DataLinq.Api__StoragePath: /data/storage
      DataLinq.CodeApi__AccessTokenIssuer: http://localhost:6789
      DataLinq.CodeApi__ClientEndpoints__0: http://localhost:5678
    volumes:
      - E:\temp\datalinq:/data/storage